<?php
/**
 * Canonical vanilla-PHP client for the CE Support help desk.
 * Generated by the wire-ce-support skill. Do not edit by hand — re-run the skill.
 *
 * For plain-PHP sites with no framework (kevinchamplin.com class, custom PHP apps).
 *
 * Installation:
 *   - Drop this file somewhere reachable (e.g. /opt/ce-support/ce-support.php).
 *   - Set these env vars in your apache/nginx vhost or the PHP-FPM pool:
 *       CE_SUPPORT_BASE         = https://support.champlinenterprises.com
 *       CE_SUPPORT_PRODUCT_SLUG = <your-slug>
 *       CE_SUPPORT_API_SECRET   = <the rotated secret>
 *
 *     OR define() the same names in a bootstrap file you already require.
 *
 * Usage from anywhere:
 *   require_once '/opt/ce-support/ce-support.php';
 *   $r = ce_support_file_ticket([
 *       'customer_email' => $email,
 *       'subject'        => 'Site broke after the redesign',
 *       'body'           => $details,
 *   ]);
 *   // $r['ticket']['public_id'], $r['ticket']['portal_url']
 */

if (! function_exists('ce_support_file_ticket')) {

    function ce_support_file_ticket(array $args): array {
        $defaults = [
            'customer_email'    => '',
            'customer_name'     => null,
            'subject'           => '',
            'body'              => '',
            'priority'          => 'normal',
            'send_confirmation' => true,
        ];
        $payload = array_intersect_key(array_merge($defaults, $args), $defaults);

        return _ce_support_signed_request('POST', '/api/v1/tickets', json_encode($payload, JSON_UNESCAPED_SLASHES));
    }

    function ce_support_get_ticket(string $public_id): array {
        return _ce_support_signed_request('GET', '/api/v1/tickets/' . rawurlencode($public_id), '');
    }

    function _ce_support_signed_request(string $method, string $path, string $body): array {
        $base   = _ce_support_cfg('CE_SUPPORT_BASE');
        $slug   = _ce_support_cfg('CE_SUPPORT_PRODUCT_SLUG');
        $secret = _ce_support_cfg('CE_SUPPORT_API_SECRET');

        $ts  = (string) time();
        $msg = $ts . "\n" . $method . "\n" . ltrim($path, '/') . "\n" . hash('sha256', $body);
        $sig = hash_hmac('sha256', $msg, $secret);

        $ch = curl_init();
        curl_setopt_array($ch, [
            CURLOPT_URL            => $base . $path,
            CURLOPT_CUSTOMREQUEST  => $method,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT        => 10,
            CURLOPT_HTTPHEADER     => [
                'X-CE-Product: ' . $slug,
                'X-CE-Timestamp: ' . $ts,
                'X-CE-Signature: ' . $sig,
                'Content-Type: application/json',
                'Accept: application/json',
            ],
        ]);
        if ($method === 'POST') {
            curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
        }
        $raw    = curl_exec($ch);
        $status = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $err    = curl_error($ch);
        curl_close($ch);

        if ($raw === false) {
            return ['ok' => false, 'error' => $err];
        }
        $json = json_decode($raw, true);
        return is_array($json) ? $json : ['ok' => false, 'http_status' => $status, 'body' => $raw];
    }

    function _ce_support_cfg(string $name): string {
        if (defined($name)) {
            return (string) constant($name);
        }
        $env = getenv($name);
        if ($env !== false && $env !== '') {
            return (string) $env;
        }
        throw new RuntimeException(
            "CE Support: missing {$name}. Define it via env var or define() before requiring this file. Re-run /wire-ce-support."
        );
    }
}
